apiVersion: v1
kind: Service
metadata:
  name: nodeport-compras
  namespace: sa-p5
spec:
  selector:
    app: compras
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30004 
  type: NodePort
