apiVersion: apps/v1
kind: Deployment
metadata:
  name: compras
  namespace: sa-p5
  labels:
    app: compras
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compras
  template:
    metadata:
      labels:
        app: compras
    spec:
      containers:
      - name: compras
        image: luizz8/comprasp7
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: my-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: compras-hpa
  namespace: sa-p5
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: compras
    minReplicas: 1
    maxReplicas: 2
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80