apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateways
  namespace: sa-p5
  labels:
    app: gateways
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateways
  template:
    metadata:
      labels:
        app: gateways
    spec:
      containers:
      - name: gateways
        image: luizz8/gateways
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"