apiVersion: v1
kind: Service
metadata:
  name: nodeport-metodos
  namespace: sa-p5
spec:
  selector:
    app: metodos
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30003  
  type: NodePort
